# Stage 1: Установка неизменяемых зависимостей
FROM python:3.9 as base

# Установка дополнительных пакетов Tesseract OCR и libGL.so.1
RUN apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-rus libgl1-mesa-glx

# Копирование и установка неизменяемых зависимостей из requirements_stable.txt
COPY requirements_stable.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt